---
output:
  pdf_document: default
  html_document: default
---
```{r}
library("reticulate")
library("scales")

library("fanplot")
np <- import("numpy")
ntimepts <- 1000
burn_in_n <- 1e3
skip <- 10
home_directory <-"/Users/aarcher/PycharmProjects/13_PDO_Pathway_Inference/MCMC/"
directory <- paste(home_directory,"output/MCMC_results_formatted/adaptive/preset_std/lambda_0,01_beta_0,25/nsamples_10000/norm",sep="")
directory_plot <- paste(home_directory,"output/MCMC_results_plots/adaptive/preset_std/lambda_0,01_beta_0,25/nsamples_10000/norm/interpretation_plots/",sep="")
```

```{r}
library(readr)
time_series_df <- read_csv("~/PycharmProjects/13_PDO_Pathway_Inference/data/data_files/data_time_series_modified.csv")
```

```{r}
plot_fun <- function(plot_name, mar =  c(5.1, 7.1, 5.1, 2.1)){
png(
    file=paste(directory_plot,plot_name,sep=''),
    width     = 2.75,
    height    = 2.75,
    units     = "in",
    res       = 1200,
    pointsize = 4
)
par(
    mar      = mar,
    xaxs     = "i",
    yaxs     = "i",
    cex.axis = 1.5,
    cex.lab  = 1.5,
    cex.main = 2
)}

```

```{r}
ln = c(5, 20, 50, 80, 95)


for(gly_cond in c(50,60,70,80)){
  #data points
  rows_bool = time_series_df$`Glycerol Init (g/L)` == gly_cond
  time_samples = time_series_df[rows_bool,]$`Time (hrs)`
  time_disc = seq(0,max(time_samples),length.out=ntimepts)
  gly_samples = time_series_df[rows_bool,]$`Glycerol (mM)`

  #solutions evaluated paramter points
  data_set <- np$load(paste(directory,'/solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  filter <- rowSums(data_set[,,6] < data_set[1,1,4]) == 1000 #TODO compare the entire row to each column
  data_set <- data_set[filter,,]
  median_gly <- apply(data_set[,,4], 2, median, na.rm=T)

  median_data_set <- np$load(paste(directory,'/median_param_solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  mean_data_set <- np$load(paste(directory,'/mean_param_solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  
   plot_fun(paste('data_distribution_GLY_ext_',gly_cond,'_fan_plot_wo_param_stats.png',sep=''))
  fan0(data=data_set[,,4],xlim=c(0,max(time_samples)),ylim=c(0,max(data=data_set[,,4])), start =0, frequency = 1/(max(time_samples)/ntimepts), ln = ln,rcex=1,rstagger=TRUE,llab=FALSE,rstagger_vec=c(0.55,0.5,0.45,0.4,0.35),rpos=NULL,lpos=NULL,fan.col = colorRampPalette(c("blue", "grey", "white")),ln.col="royalblue",ylab="",xlab="")
  points(time_samples,gly_samples,pch=16)
  lines(time_disc,median_gly,lty=2)
  legend(x="topright", legend=c("experimental observations", "median model result"), lty=c(NA,2), pch=c(16,NA),cex=1,col=c('black','black'))
  title('Time series distribution of \n external glycerol concentration (mM)',ylab='External glycerol\n concentration (mM)',xlab='time (hrs)',cex=2)
  dev.off()
    
  plot_fun(paste('data_distribution_GLY_ext_',gly_cond,'_fan_plot.png',sep=''))
  fan0(data=data_set[,,4],xlim=c(0,max(time_samples)),ylim=c(0,max(data=data_set[,,4])), start =0, frequency = 1/(max(time_samples)/ntimepts), ln = ln,rcex=1,rstagger=TRUE,llab=FALSE,rstagger_vec=c(0.55,0.5,0.45,0.4,0.35),rpos=NULL,lpos=NULL,fan.col = colorRampPalette(c("blue", "grey", "white")),ln.col="royalblue",ylab="",xlab="")
  points(time_samples,gly_samples,pch=16)
  lines(time_disc,median_gly,lty=2,col=alpha("black",0.7))
  lines(time_disc,median_data_set[,4],lty=2,col=alpha("red",0.7))
  lines(time_disc,mean_data_set[,4],lty=2,col=alpha("yellow",0.7))
  legend(x="topright", legend=c("experimental observations", "median model result","model at marginal median parameter", "model at marginal mean parameter"), lty=c(NA,2,2,2), pch=c(16,NA,NA,NA),cex=1,col=c('black','black','red','yellow'))
title('Time series distribution of \n external glycerol concentration (mM)',ylab='External glycerol\n concentration (mM)',xlab='time (hrs)',cex=2)
  dev.off()
} 
 
```

```{r}
ln = c(5, 20, 50, 80, 95)


for(gly_cond in c(50,60,70,80)){
  #data points
  rows_bool = time_series_df$`Glycerol Init (g/L)` == gly_cond
  time_samples = time_series_df[rows_bool,]$`Time (hrs)`
  time_disc = seq(0,max(time_samples),length.out=ntimepts)
  pdo_samples = time_series_df[rows_bool,]$`PDO (mM)`

  #solutions evaluated paramter points
  data_set <- np$load(paste(directory,'/solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  filter <- rowSums(data_set[,,6] < data_set[1,1,4]) == 1000 #TODO compare the entire row to each column
  data_set <- data_set[filter,,]
  median_pdo <- apply(data_set[,,6], 2, median, na.rm=T)
  median_data_set <- np$load(paste(directory,'/median_param_solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  mean_data_set <- np$load(paste(directory,'/mean_param_solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  
   plot_fun(paste('data_distribution_13PDO_ext_',gly_cond,'_fan_plot_wo_param_stats.png',sep=''), mar = c(5.1, 6.1, 4.1, 4.1))
  fan0(data=data_set[,,6],xlim=c(0,max(time_samples)+1),ylim=c(0,max(data=data_set[,,4])), start =0, frequency = 1/(max(time_samples)/ntimepts), ln = ln,rcex=0.85,rstagger=FALSE,llab=FALSE,rpos=4,lpos=NULL,fan.col = colorRampPalette(c("blue", "grey", "white")),ln.col="royalblue",ylab="",xlab="")
  points(time_samples,pdo_samples,pch=16)
  median_pdo <- apply(data_set[,,6], 2, median, na.rm=T)
  lines(time_disc,median_pdo,lty=2)
  legend(x="topright", legend=c("experimental observations", "median model result"), lty=c(NA,2), pch=c(16,NA),cex=1,col=c('black','black'))
  title('Time series distribution of \n external 1,3-PDO concentration (mM)',ylab='External 1,3-PDO\n concentration (mM)',xlab='time (hrs)',cex=2)
  dev.off()
    
  plot_fun(paste('data_distribution_13PDO_ext_',gly_cond,'_fan_plot.png',sep=''))
    fan0(data=data_set[,,6],xlim=c(0,max(time_samples)+1),ylim=c(0,max(data=data_set[,,4])), start =0, frequency = 1/(max(time_samples)/ntimepts), ln = ln,rcex=0.85,rstagger=FALSE,llab=FALSE,rpos=4,lpos=NULL,fan.col = colorRampPalette(c("blue", "grey", "white")),ln.col="royalblue",ylab="",xlab="")
  points(time_samples,pdo_samples,pch=16)
  lines(time_disc,median_pdo,lty=2,col=alpha("black",0.7))
  lines(time_disc,median_data_set[,6],lty=2,col=alpha("red",0.7))
  lines(time_disc,mean_data_set[,6],lty=2,col=alpha("yellow",0.7))
  legend(x="topright", legend=c("experimental observations", "median model result","model at marginal median parameter", "model at marginal mean parameter"), lty=c(NA,2,2,2), pch=c(16,NA,NA,NA),cex=1,col=c('black','black','red','yellow'))
title('Time series distribution of \n external 1,3-PDO concentration (mM)',ylab='External 1,3-PDO\n concentration (mM)',xlab='time (hrs)',cex=2)
  dev.off()
} 
 
```

```{r}
MBC = 8.5 #TODO double check this value
MIC= 1.5 #TODO double check this value
ln = c(5, 20, 50, 80, 95)

for(gly_cond in c(50,60,70,80)){
 #solutions evaluated paramter points
  data_set <- np$load(paste(directory,'/solution_array_burn_in_',burn_in_n,'_skip_', skip,'_ntimepts_',ntimepts, '_init_cond_',gly_cond,'.pkl',sep=''),allow_pickle=TRUE)
  filter <- rowSums(data_set[,,6] < data_set[1,1,4]) == 1000 #TODO compare the entire row to each column
  data_set <- data_set[filter,,]
  HPA_data_set <- pmax(data_set[,,2],10^(-10))
  log_HPA_data_set <- log10(HPA_data_set)
  median_log_HPA <- apply(log_HPA_data_set, 2, median, na.rm=T)
  median_param_log_HPA <- log10(pmax(median_data_set[,2],10^(-10)))
  mean_param_log_HPA <- log10(pmax(mean_data_set[,2],10^(-10)))
    plot_fun(paste('data_distribution_3HPA_cyto_',gly_cond,'_fan_plot.png',sep=''),mar=c(5.1, 6.1, 4.1, 2.1))
    fan0(data=log_HPA_data_set,xlim=c(0,max(time_samples)),ylim=c(min(log_HPA_data_set),max(data=log_HPA_data_set)),ylab='Cytosolic 3-HPA \n concentration (mM)',xlab='time (hrs)',  start =0, frequency = 1/(max(time_samples)/ntimepts), ln = ln,rcex=1,rstagger=TRUE,rstagger_vec=c(0.65,0.6,0.55,0.5,0.45),llab=FALSE,rpos=NULL,lpos=NULL,fan.col = colorRampPalette(c("royalblue", "grey", "white")))
  title('Time series distribution of \n cytosolic 3-HPA concentration (mM)')
  lines(time_disc,median_log_HPA,lty=2,col=alpha("black",0.6))
  lines(time_disc,median_param_log_HPA,lty=2,col=alpha("red",0.6))
  lines(time_disc,mean_param_log_HPA,lty=2,col=alpha("yellow",0.6))
  legend("topright", legend=c("median model result","model at marginal median parameter", "model at marginal mean parameter"), lty=c(2,2,2), pch=c(NA,NA,NA),cex=1, col=c('black','red','yellow'))
    dev.off()
    plot_fun(paste('data_distribution_3HPA_MIC_MBC_cyto_',gly_cond,'_fan_plot.png',sep=''), mar=c(5.1, 6.1, 4.1, 4.1))
    fan0(data=log_HPA_data_set,xlim=c(0,max(time_samples)),ylim=c(min(log_HPA_data_set),log10(50)),ylab='Cytosolic 3-HPA \n concentration (mM)',xlab='time (s)', ln = c(10, 20, 30, 40, 50, 60, 70, 80, 90), start =0, frequency = 1/(max(time_samples)/ntimepts), rcex=1,rstagger=TRUE,rstagger_vec=c(0.6,0.55,0.5,0.45,0.4,0.35,0.3,0.25,0.2),llab=FALSE,rpos=NULL,lpos=NULL,fan.col = colorRampPalette(c("royalblue", "grey", "white")))
    abline(h=log10(MIC), lty=2,col=alpha("black",0.6))
    abline(h=log10(MBC), lty=2,col=alpha("black",0.6))
    axis(4, at=c(log10(MIC),log10(MBC)),labels=c('MIC','MBC'), las=2,cex.axis=1.5)
    lines(time_disc,median_log_HPA,lty=2,col=alpha("black",0.6))
    lines(time_disc,median_param_log_HPA,lty=2,col=alpha("red",0.6))
    lines(time_disc,mean_param_log_HPA,lty=2,col=alpha("yellow",0.6))
    legend(x=1,y=-8.25, legend=c("median model result","model at marginal median parameter", "model at marginal mean parameter"), lty=c(2,2,2), pch=c(NA,NA,NA),cex=1, col=c('black','red','yellow'))
    title('Time series distribution of \n cytosolic 3-HPA concentration (mM)')
    dev.off()
  }
```